name: Check Formatting and Build

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - 'release-please--*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Check formatting
        run: npm run format:check
      - name: Build
        run: npm run build
